version: 0.2
phases:
  pre_build:
    commands:
      - REPOSITORY_URI=public.ecr.aws/s5o7d0z2/sanjay-php
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_NUMBER | awk -F":" '{print $2}')
  build:
    commands:
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/s5o7d0z2
      - docker push public.ecr.aws/s5o7d0z2/sanjay-php:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - printf '[{"name":"sanjay-php","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
   - imagedefinitions.json
